FROM osrf/ros:noetic-desktop-full
 
# Change the default shell to Bash
SHELL [ "/bin/bash" , "-c" ]
 
# Install Git
RUN apt-get update && apt-get install -y git
 
# Create a Catkin workspace and clone TurtleBot3 repos
RUN source /opt/ros/noetic/setup.bash \
 && git clone https://github.com/iamrajee/droneai_ws \
 && cd /droneai_ws/ \
 && chmod +x *.sh \

# Build the Catkin workspace and ensure it's sourced
RUN source /opt/ros/noetic/setup.bash \
 && cd droneai_ws \
 && catkin_make
RUN echo "source /droneai_ws/devel/setup.bash" >> ~/.bashrc
 
# Set the working folder at startup
WORKDIR /droneai_ws